
[build]
target = "x86_64.json"

[target.'cfg(target_os = "none")']
rustflags = ["-C", "link-args=--entry=kernel"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]