
[build]
target = "x86_64-efi.json"

[target.'cfg(target_os = "none")']
#runner = "ls"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:uefi_start /SUBSYSTEM:EFI_Application"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e uefi_start -static -nostartfiles"]