[package]
name = "cherimoya-bootloader"
version = "0.0.1"
authors = ["AidoP <aidop@me.com>"]
edition = "2018"

[dependencies]
kalloc = { path = "../kalloc" }
elf64 = { git = "https://github.com/AidoP/elf64", branch = "main" }